spring:
  datasource:
    url: jdbc:mysql://naedonnaepick-db.chccokm84j4g.ap-northeast-2.rds.amazonaws.com:3306/naedonnaepick_db?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: "*psy0605751*"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

flask:
  recommend:
    url: http://localhost:5000/api/predict